version: 2.1
orbs:
  apptest-ai: apptestai/android-app-test@volatile

jobs:
  build-android:
    macos:
      xcode: 11.3.1
    steps:
      - checkout
      - run:
          name: install android-sdk
          command: |
            brew cask install android-sdk
            yes | /usr/local/share/android-sdk/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3" "platform-tools" "ndk-bundle" || true
      - run:
          name: install xamarin 
          command: brew cask install xamarin xamarin-android visual-studio
      - run:
          name: create keystore file
          command: echo "$SIGNING_KEY" | base64 --decode > ${HOME}/keystore.jks
      - run:
          name: nuget restore
          working_directory: ./HackerNews
          command: nuget restore
      - run:
          name: build
          working_directory: ./HackerNews/HackerNews.Droid
          command: |
            ANDROID_HOME="/usr/local/share/android-sdk"
            ANDROID_NDK_HOME="/usr/local/share/android-sdk/ndk-bundle"
            ANDROID_NDK_PATH="/usr/local/share/android-sdk/ndk-bundle"
            KEY_STORE_FILE="${HOME}/keystore.jks"
            msbuild "HackerNews.Droid.csproj" "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidNdkDirectory=$ANDROID_NDK_PATH" "/p:AndroidSdkDirectory=$ANDROID_HOME" "/p:AndroidSigningKeyAlias=$ALIAS" "/p:AndroidSigningKeyPass=$KEY_PASSWORD" "/p:AndroidSigningKeyStore=$KEY_STORE_FILE" "/p:AndroidSigningStorePass=$KEY_STORE_PASSWORD"
      - apptest-ai/run-test:
          binary_path: "HackerNews/HackerNews.Droid/bin/Release/com.minnick.HackerNews-Signed.apk"
          project_id: "1134"
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

  build-ios:
    macos:
      xcode: 11.3.1
    steps:
      - checkout
      - run:
          name: install brew cask
          command: brew cask install xamarin xamarin-ios visual-studio
      - run:
          name: nuget restore
          working_directory: ./HackerNews
          command: nuget restore
      - run:
          name: Prepare build
          working_directory: ./HackerNews/HackerNews.iOS
          command: |
            bundle update --bundler
            fastlane add_plugin souyuz
      - run:
          name: build
          working_directory: ./HackerNews/HackerNews.iOS
          command: fastlane beta
      - apptest-ai/run-test:
          binary_path: "HackerNews/HackerNews.iOS/bin/iPhone/Release/HackerNews.iOS.ipa"
          project_id: "1137"
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results

workflows:
    build-and-test:
      jobs:
        - build-android
        - build-ios
